### PR TITLE
Replaces invocations of dplyr deprecated funcs with supported

### LINKED ISSUE #250: Warning message: select_() is deprecated as of dplyr 0.7.0
Hello, I'm reporting this warning message related to RNeXML:

```
> nexml_ontotrace <- pk_get_ontotrace(nexml)
Warning message:
`select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

```
> lifecycle::last_warnings()
[[1]]
<deprecated>
message: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
backtrace:
  1. rphenoscape::pk_get_ontotrace(nexml)
  2. RNeXML::get_characters(...)
  6. RNeXML::get_level(nex, "otus/otu")
  4. recursion(1, lvl)(nex)
 12. dplyr::select_(., quote(-nexml))
 16. dplyr:::lazy_deprec("select", hint = FALSE)
```
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rphenoscape_0.2.15

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     xml2_1.3.2       magrittr_1.5     uuid_0.1-4       tidyselect_1.1.0 ape_5.3          lattice_0.20-41 
 [8] R6_2.4.1         rlang_0.4.8      stringr_1.4.0    httr_1.4.1       plyr_1.8.6       dplyr_1.0.2      tools_4.0.2     
[15] parallel_4.0.2   RNeXML_2.4.3     grid_4.0.2       nlme_3.1-148     ellipsis_0.3.0   lazyeval_0.2.2   tibble_3.0.1    
[22] lifecycle_0.2.0  crayon_1.3.4     tidyr_1.0.2      purrr_0.3.4      reshape2_1.4.4   vctrs_0.3.4      curl_4.3        
[29] glue_1.4.0       stringi_1.4.6    compiler_4.0.2   pillar_1.4.4     generics_0.0.2   XML_3.99-0.3     jsonlite_1.6.1  
[36] pkgconfig_2.0.3 

```

### PR DESCRIPTION
**Pull request by hlapp**
In particular, the replacements concern select_(), mutate_(), and rename_() invocations.

As a result, this drops one dependency (lazyeval::interp), and some expressions are aguably clearer than they were before.

Fixes #250.

### CODE REVIEW

**Comment by hlapp** [comment]
Looks like someone needs to update the CircleCI test configuration?

**Comment by cboettig** [comment]
yeah I think CircleCI and appveyor are basically deprecated, need to figure out how to deactivate those hooks.

Not sure what is behind the other two failing checks, though looks like it could be connected to potentially broken functionality in the taxize helper?

**Comment by hlapp** [comment]
> Not sure what is behind the other two failing checks, though looks like it could be connected to potentially broken functionality in the taxize helper?

Yes that's what it looks like. I checked and confirmed that the input (the taxon labels extracted from the nexml object) to the `taxalight::get_ids()` call is correct.

**Comment by cboettig** [comment]
ok thanks.  merging this, and can take a look at the taxalight call later since it's an unrelated issue anyway.  as it's passing on some of the platforms it might just be an issue with LMDB config

**Pull request merged**
