### PR TITLE
Change fig.path in README.Rmd so output is in tools

### LINKED ISSUE #160: Address CRAN request re README.md images
Output graphs from the `.Rmd` should be in `/tools` subdir and not be `.Rbuildignore`'d.  This way the .md can be rendered to HTML on CRAN.

### PR DESCRIPTION
**Pull request by amoeba**
This addresses a CRAN comment and allows CRAN to render the README.md as HTML for their purposes

Closes #160 on upstream

### CODE REVIEW

**Comment by cboettig** [comment]
Nice, thanks for that! @amoeba you doing anything with NeXML or just being super helpful?

**Comment by amoeba** [comment]
Just stumbled across the Issue while scanning for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) PRs.

**Comment by cboettig** [comment]
Cool.  I think you'd enjoy reading the original [NeXML schema paper](https://www.ncbi.nlm.nih.gov/pubmed/22357728), as an XML schema that was created about a decade later than EML, which is reflected in it's style (e.g. a strong design around extensibility, semantic / linked data concepts, and the use of rdf-a style `meta` elements).  

Unlike EML, it is intended to encode the data as well as the metadata -- in fact it's an interesting case study in that it was taking aim at a (still dominant?) way of encoding phylogenetic trees; the NEXUS format; which as the paper does a great job of highlighting, isn't actually a consistent standard (largely due to the conflicting ways different developers have tried to extend it).  Anyway, I think you'd enjoy the paper

**Comment by amoeba** [comment]
Thanks for the link! The package looked cool from the README but I hadn't really taken a good look yet. Will read!

**Pull request merged**
