### PR TITLE
changes to nexml_read

### PR DESCRIPTION
**Pull request by sckott**
switch to generic S3 function, with methods for character, XMLInternalDocument and XMLInternalNode
added more examples for all the possible inputs
changed character input checking to hopefully fail well when character input not appropriate

addresses #123

@cboettig feel free to not accept this - there may be good reason not to switch approaches that I'm not thinking of. Can add tests, where's the best place to put those?

### CODE REVIEW

**Comment by cboettig** [comment]
Nice.  Can you add a test that shows this fixes the bug in #123?

**Comment by sckott** [comment]
yeah

**Comment by sckott** [comment]
added

**Comment by hlapp** [comment]
Looks great!

**Comment by xu-hong** [comment]
It works great! Just changed the reading nexml part [https://github.com/xu-hong/rphenoscape/commit/38eb615e8dbc041b9e814e584cad817a52f220b4] (https://github.com/xu-hong/rphenoscape/commit/38eb615e8dbc041b9e814e584cad817a52f220b4) in rPhenoscape @hlapp

**Pull request merged**
