### PR TITLE
Fixes duplicate S4 class name issues without changing class names

### LINKED ISSUE #169: clash with "tree" class name provided by cli package
Trying to load [this file](https://github.com/ropensci/RNeXML/files/2393110/file6727d10af7.txt) (from OpenTree), I get:

```
Found more than one class "tree" in cache; using the first, from namespace 'cli'
Also defined by ‘RNeXML’
Found more than one class "tree" in cache; using the first, from namespace 'cli'
Also defined by ‘RNeXML’
Error in validObject(.Object) : 
  invalid class “MethodWithNext” object: invalid object for slot "nextMethod" in class "MethodWithNext": got class "NULL", should be or extend class "PossibleMethod"
```

### LINKED ISSUE #183: Various test failures with devtools::test()
Although tests seem to be passing with `R CMD check` (including locally), there are a variety of failures with `devtools::test()`, which is the command that the "Test package" command in RStudio runs.

I don't understand why the difference, but it's a little troubling.

Output from the failures follows. (The output is modified from the original. Specifically, I removed various warnings, reports on successful tests, and left only the failures.)

```
Testing RNeXML
✖ |  7 5     | ape [2.5 s]
test_ape.R:30: error: From nexml to multiPhylo
'names' attribute [2] must be the same length as the vector [0]
1: expect_warning(phy <- as(nexml, "phylo"), "Multiple trees found, Returning multiPhylo object") at /Users/lapp/Projects/RNeXML/tests/testthat/test_ape.R:30
2: quasi_capture(enquo(object), capture_warnings, label = label)
3: capture(act$val <- eval_bare(get_expr(quo), get_env(quo)))
4: withCallingHandlers(code, warning = function(condition) {
       out$push(condition)
       invokeRestart("muffleWarning")
   })
5: eval_bare(get_expr(quo), get_env(quo))
6: as(nexml, "phylo")
7: asMethod(object)
8: as(from, "multiPhylo") at /Users/lapp/Projects/RNeXML/R/get_trees.R:106
9: asMethod(object)
10: unname(lapply(from@trees, function(X) {
       out <- unname(lapply(X@tree, toPhylo, map[[X@otus]]))
       class(out) <- "multiPhylo"
       out
   })) at /Users/lapp/Projects/RNeXML/R/get_trees.R:73
11: lapply(from@trees, function(X) {
       out <- unname(lapply(X@tree, toPhylo, map[[X@otus]]))
       class(out) <- "multiPhylo"
       out
   })
12: FUN(X[[i]], ...)
13: unname(lapply(X@tree, toPhylo, map[[X@otus]])) at /Users/lapp/Projects/RNeXML/R/get_trees.R:75
14: lapply(X@tree, toPhylo, map[[X@otus]])
15: FUN(X[[i]], ...)

test_ape.R:53: error: We can read and write NeXML to phylo and back without edge.lengths
'names' attribute [2] must be the same length as the vector [0]
1: as(nexml_read("ex.xml"), "phylo") at /Users/lapp/Projects/RNeXML/tests/testthat/test_ape.R:53
2: asMethod(object)
3: toPhylo(from@trees[[1]]@tree[[1]], maps[[otus_id]]) at /Users/lapp/Projects/RNeXML/R/get_trees.R:103

test_ape.R:66: error: Rooted trees remain rooted on conversions
'names' attribute [2] must be the same length as the vector [0]
1: expect_true(is.rooted(as(read.nexml("tmp.xml"), "phylo"))) at /Users/lapp/Projects/RNeXML/tests/testthat/test_ape.R:66
2: quasi_label(enquo(object), label)
3: eval_bare(get_expr(quo), get_env(quo))
4: is.rooted(as(read.nexml("tmp.xml"), "phylo"))
5: as(read.nexml("tmp.xml"), "phylo")
6: asMethod(object)
7: toPhylo(from@trees[[1]]@tree[[1]], maps[[otus_id]]) at /Users/lapp/Projects/RNeXML/R/get_trees.R:103

test_ape.R:75: error: Unrooted trees remain unrooted on conversions
'names' attribute [2] must be the same length as the vector [0]
1: expect_false(is.rooted(as(read.nexml("tmp.xml"), "phylo"))) at /Users/lapp/Projects/RNeXML/tests/testthat/test_ape.R:75
2: quasi_label(enquo(object), label)
3: eval_bare(get_expr(quo), get_env(quo))
4: is.rooted(as(read.nexml("tmp.xml"), "phylo"))
5: as(read.nexml("tmp.xml"), "phylo")
6: asMethod(object)
7: toPhylo(from@trees[[1]]@tree[[1]], maps[[otus_id]]) at /Users/lapp/Projects/RNeXML/R/get_trees.R:103

test_ape.R:81: error: We can convert trees with only some edge lengths into ape::phylo
'names' attribute [2] must be the same length as the vector [0]
1: expect_warning(a <- as(read.nexml(f), "phylo"), "Multiple trees found, Returning multiPhylo object") at /Users/lapp/Projects/RNeXML/tests/testthat/test_ape.R:81
2: quasi_capture(enquo(object), capture_warnings, label = label)
3: capture(act$val <- eval_bare(get_expr(quo), get_env(quo)))
4: withCallingHandlers(code, warning = function(condition) {
       out$push(condition)
       invokeRestart("muffleWarning")
   })
5: eval_bare(get_expr(quo), get_env(quo))
6: as(read.nexml(f), "phylo")
7: asMethod(object)
8: as(from, "multiPhylo") at /Users/lapp/Projects/RNeXML/R/get_trees.R:106
9: asMethod(object)
10: unname(lapply(from@trees, function(X) {
       out <- unname(lapply(X@tree, toPhylo, map[[X@otus]]))
       class(out) <- "multiPhylo"
       out
   })) at /Users/lapp/Projects/RNeXML/R/get_trees.R:73
11: lapply(from@trees, function(X) {
       out <- unname(lapply(X@tree, toPhylo, map[[X@otus]]))
       class(out) <- "multiPhylo"
       out
   })
12: FUN(X[[i]], ...)
13: unname(lapply(X@tree, toPhylo, map[[X@otus]])) at /Users/lapp/Projects/RNeXML/R/get_trees.R:75
14: lapply(X@tree, toPhylo, map[[X@otus]])
15: FUN(X[[i]], ...)
─────────────────────────────────────────
✖ |  1 1     | Comparative analysis [2.6 s]
test_comp_analysis.R:9: error: We can extract tree and trait data to run fitContinuous and fitDiscrete
'names' attribute [2] must be the same length as the vector [0]
1: get_trees(nexml) at /Users/lapp/Projects/RNeXML/tests/testthat/test_comp_analysis.R:9
2: as(nexml, "phylo") at /Users/lapp/Projects/RNeXML/R/get_trees.R:38
3: asMethod(object)
4: toPhylo(from@trees[[1]]@tree[[1]], maps[[otus_id]]) at /Users/lapp/Projects/RNeXML/R/get_trees.R:103
──────────────────────────────────────────────⠏ |  6 2 2   | metaNamespace prefix xhtml on div is not defined
✖ |  9 2 2   | meta [6.0 s]
Validation failed, error messages: 
                    tree 'uuid-59ed239e-71db-42f4-8391-fbfcda72e3c9' has reticulations            Validation failed, error messages: 
                    tree 'uuid-59ed239e-71db-42f4-8391-fbfcda72e3c9' has reticulations (line 46)
            

test_meta.R:31: failure: We can add R bibentry type metadata
`o` isn't true.

test_meta.R:60: warning: We can add additional metadata
Validation failed, error messages: 
                    tree 'uuid-535cc64b-9185-447b-8ef6-aa9c3c774055' has reticulations            Validation failed, error messages: 
                    tree 'uuid-535cc64b-9185-447b-8ef6-aa9c3c774055' has reticulations (line 49)
            

test_meta.R:60: failure: We can add additional metadata
`o` isn't true.
──────────────────────────────────────────────✖ |  0 2 2   | serializing [3.5 s]
Validation failed, error messages: 
                    tree 'uuid-11851ccd-7fba-4f49-9311-49c881c0fec5' has reticulations            Validation failed, error messages: 
                    tree 'uuid-11851ccd-7fba-4f49-9311-49c881c0fec5' has reticulations (line 32)
            

test_serializing.R:15: failure: We can serialize ape to S4 RNeXML into valid NeXML
`o` isn't true.

Validation failed, error messages: 
                    tree 'tree1' has reticulations            Validation failed, error messages: 
                    tree 'tree1' has reticulations (line 15)
  
test_serializing.R:29: failure: We can serialize parsed NeXML to S4 RNeXML into valid NeXML
`o` isn't true.
```

### PR DESCRIPTION
**Pull request by hlapp**
It turns out that S4 classes defined with the same name but in different packages are actually supported in R. Hence, pseudo-namespacing class names as proposed in the #201 change set should in principle not be required. The mechanism for namespacing a class is in essence through the `package` attribute of the class name string. The function `packageSlot()` can be used to query and set the package attribute, and the function `className()` generates a class name namespaced in this way from its two arguments.

Therefore, this would allow us to keep the class names we want, not have to worry about adding and stripping the pseudo-namespace to/from the class name, and maintain full backward compatibility. All we would have to do is use `new(className(name, "RNeXML"))` instead of `new(name)`.

However, that's unfortunately only the theory. In practice, two things are at least currently broken, preventing this to be sufficient to make it work:
* `callNextMethod()`, which is the key mechanism to recurse a generic down the inheritance chain, internally calls `addNextMethod()` in order to  find and record the next method to be called in the chain. That  function is passed all the information it would need (package names  for namespacing super classes etc), but somehow it nonetheless  errors out if at least the first argument in the signature is a class  that's duplicated in another package.
* S4 generics dispatch, which is the key mechanism to find the appropriate method for a given set of arguments, somehow at some point loses the  correct method for a signature in its lookup table if at least the first  argument is of a class that's duplicated in another package.

This change set breaks down into three parts:
1. Create a convenience function `New()` that ensures the class name is properly namespaced. This solves the problem of making invocation of `new()` unambiguous.
2. Create a function that does the work of finding the next method that addNextMethod() should be doing instead, and caching the result in  the calling environment in a way that callNextMethod() picks it up  and then bypasses the invocation of `addNextMethod()`.
3. Create a function that finds the right method for an S4 generic, in the way `standardGeneric()` should be doing but doesn't in certain cases.

To be clear, as a full alternative to #201 this, too, fixes #169 and fixes #183. Unlike #201, it does not eliminate all messages of the _Found more than one class "tree" in cache; using the first, from namespace 'cli'. Also defined by ‘RNeXML’_ kind. However, so far these messages have not correlated with adverse events or results. It looks like they are being generated in the context of the call to `initialize()`, an S4 generic, which is at the end of the `new()` implementation in the methods package.

The other difference to #201 is that the protection from duplicated class names isn't sweeping. I have purposely applied it here only to the `tree` class, the one that presently happens to cause the issues. The protection _could_ be applied on a sweeping basis, but the reasons I haven't (yet) are the following:
* No class name changes, and hence aiming for consistency across the visible class hierarchy is not really a factor.
* Applying the protection mechanism to only the actual trouble maker makes for a more narrowly scoped and hopefully easier to review PR.
* The functions that work around bugs in the methods package _try_ to emulate the behavior that should be happening in the absence of those bugs, but they're almost certainly much less sophisticated, and perhaps also a little slower about it. Their behavior might be different from the supposed behavior in some situations.
* Therefore, once those bugs in methods are corrected, we will want to remove those workarounds again.

That said, not using namespace class names for invocations of `new()` could be considered a bug, and hence this (using `New()` as a convenience method) should arguably made as a sweeping change across the hierarchy.

### CODE REVIEW

**Comment by hlapp** [comment]
@cboettig I think with the additional tests this is pretty solid now. BTW your codecov targets are pretty ambitious 😮

**Comment by cboettig** [comment]
This is awesome, had no idea such a work-around would be feasible with the `package` slot.  Does seem like a bug in the S4 system though that the core functions do respect this?  Do you have a minimal reproducible example handy regarding the behavior of generics and the callNextMethod in this case? Wonder if it's worth filing a bug report in `methods`?  

Otherwise, this looks great, so merge when ready.

I believe the coverage targets are merely codecov defaults, looks like we [can adjust](https://docs.codecov.io/docs/codecov-yaml) `codecov.yml` file to something more appropriate for the test suite, just haven't tried.

**Comment by hlapp** [comment]
> Do you have a minimal reproducible example handy regarding the behavior of generics and the callNextMethod in this case?

Not really. I tracked it down by stepping through it in the debugging `browser()`, first under conditions under which the class name was not duplicated, then under conditions in which it was duplicated.

I was wondering how one could write a test case, perhaps through evaluation of a code snippet using two environments created from scratch. I'm not sure when I have time to give that a try.

To be clear, using the specific packages "cli" and "RNeXML", the problem _can_ actually be reliably reproduced for `addNextMethod()`:

```R
library(methods)
library(RNeXML)
library(cli)
pkg <- asNamespace("RNeXML")
f <- getGeneric("toNeXML", where = pkg)
m <- selectMethod(f, signature = c(className("tree", "RNeXML"), "XMLInternalElementNode"))
mn <- addNextMethod(m, f = f, envir = pkg)
#> Found more than one class "tree" in cache; using the first, from namespace 'cli'
#> Also defined by ‘RNeXML’
#> Found more than one class "tree" in cache; using the first, from namespace 'cli'
#> Also defined by ‘RNeXML’
#> Error in validObject(.Object) : 
#>   invalid class “MethodWithNext” object: invalid object for slot "nextMethod" in class "MethodWithNext": got class "NULL", should be or extend class "PossibleMethod"
```

As you can see, there are no naked (lacking package namespace) "tree" class names in this snippet that could have been blamed.
 
> Wonder if it's worth filing a bug report in `methods`?

Yes, but I'm not sure when I'll have the time. And because I don't want to expect everyone using the RNeXML package to have to be on the latest R point release, the workaround is good to have anyway, I think.

**Comment by hlapp** [comment]
OK I'll go ahead and merge ☺️

**Comment by cboettig** [comment]
👏 yay!

Meanwhile I'll ping some folks that frequently work with S4 methods and see if anything jumps out at them.  But regardless this work-around does look like the way to go for our situation.

**Pull request merged**
